stages:
  - test
  - lint

test app:
  image: python:latest
  stage: test
  script:
    - cd python
    - python tests.py

eslint :
  image: node
  stage : lint
  script:
    - cd bettertimetable-app/src/
    - npm install --progress=false
    - ./node_modules/.bin/eslint . --ext '.js'