stages:
  - test
  - lint

test app:
  image: python:latest
  stage: test
  script:
    - cd python
    - python tests.py

eslint :
  image: node
  stage : lint
  script:
    - cd bettertimetable-app/src/
    - npm i eslint
    - node_modules/eslint/bin/eslint.js . --ext '.js'