stages:
  - test
  - lint
  - build
cache:
  paths:
    - bettertimetable-app/node_modules/

test app:
  image: python:latest
  stage: test
  script:
    - cd code/python
    - pip install flask
    - pip install beautifulsoup4
    - pip install requests
    - pip install flask-sqlalchemy
    - python tests.py

eslint :
  image: node:latest
  stage : lint
  script:
    - cd code/bettertimetable-app
    - npm install
    - npm install -g eslint 
    - npm install babel-eslint --save-dev
    - npm install eslint-plugin-flowtype --save-dev
    - npm install typescript --save-dev
    - npm install -g eslint-plugin-react
    - node_modules/.bin/eslint src/. --ext '.js'

build app:
  image: node:latest
  stage: build
  script:
    - cd code/bettertimetable-app
    - npm install
    - npm i react-scripts
    - npm run-script build
