stages:
  - test
  - lint

test app:
  image: python:latest
  stage: test
  script:
    - cd python
    - python tests.py

eslint :
  image: node:latest
  stage : lint
  script:
    - npm install -g eslint eslint-plugin-react eslint-config-airbnb
    - cd bettertimetable-app/src
    - eslint Timetable.js
    - eslint index.js