stages:
  # - test
  - lint
cache:
  paths:
    -bettertimetable-app/node_modules/
# test app:
#   image: python:latest
#   stage: test
#   script:
#     - cd python
#     - python tests.py

eslint :
  image: node:latest
  stage : lint
  script:
    - cd bettertimetable-app
    - npm install eslint eslint-plugin-react
    - node_modules/.bin/eslint src/. --ext '.js'
