stages:
  # - test
  - lint

# test app:
#   image: python:latest
#   stage: test
#   script:
#     - cd python
#     - python tests.py

eslint :
  image: node:latest
  stage : lint
  script:
    - cd bettertimetable-app
    - node_modules/.bin/eslint src/. --ext '.js'
